### ISSUE TITLE
Wallet api error

### ISSUE THREAD

**Issue by inlorite** [walt-id/waltid-identity#383]
Hi, everything used to work fine in older releases but I've redownloaded the latest release v.0.2.0 for learning purposes and while trying to launch everything through docker-compose the wallet-api container exits with an error for some reason. This is the error:

```
docker-compose-wallet-api-1         | 84 [main] INFO id.walt.webwallet.Main - Starting walt.id wallet...
docker-compose-wallet-api-1         | 98 [main] DEBUG id.walt.webwallet.Main - Running in path: /waltid-wallet-api/.
docker-compose-wallet-api-1         | 99 [main] INFO id.walt.webwallet.Main - Reading configurations...
docker-compose-wallet-api-1         | 107 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading configurations...
docker-compose-wallet-api-1         | 295 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading required configuration: "db" (DatabaseConfiguration)...
docker-compose-wallet-api-1         | 1535 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading required configuration: "web" (WebConfig)...
docker-compose-wallet-api-1         | 1650 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading required configuration: "logins" (LoginMethodsConfig)...
docker-compose-wallet-api-1         | 1716 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading required configuration: "auth" (AuthConfig)...
docker-compose-wallet-api-1         | 1785 [main] ERROR id.walt.webwallet.config.ConfigManager - ---- vvv Configuration error vvv ----
docker-compose-wallet-api-1         | Could not load configuration for "auth": com.sksamuel.hoplite.ConfigException: Error loading config because:
docker-compose-wallet-api-1         |
docker-compose-wallet-api-1         |     - Could not instantiate 'id.walt.webwallet.config.AuthConfig' because:
docker-compose-wallet-api-1         |
docker-compose-wallet-api-1         |         - 'encryptionKey': Missing from config
docker-compose-wallet-api-1         |
docker-compose-wallet-api-1         |         - 'signKey': Missing from config
docker-compose-wallet-api-1         |
docker-compose-wallet-api-1         |         - 'tokenKey': Missing from config
docker-compose-wallet-api-1         |
docker-compose-wallet-api-1         |         - 'issTokenClaim': Missing from config
docker-compose-wallet-api-1         |
docker-compose-wallet-api-1         |         - 'audTokenClaim': Missing from config
docker-compose-wallet-api-1         |   at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:247)
docker-compose-wallet-api-1         |   at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:244)
docker-compose-wallet-api-1         |   at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
docker-compose-wallet-api-1         |   at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:244)
docker-compose-wallet-api-1         |   at com.sksamuel.hoplite.ConfigLoader.loadConfigOrThrow(ConfigLoader.kt:118)
docker-compose-wallet-api-1         |   at id.walt.webwallet.config.ConfigManager.loadConfig(ConfigManager.kt:49)
docker-compose-wallet-api-1         |   at id.walt.webwallet.config.ConfigManager.loadConfigs(ConfigManager.kt:155)
docker-compose-wallet-api-1         |   at id.walt.webwallet.MainKt.main(Main.kt:29)
docker-compose-wallet-api-1         |   at id.walt.webwallet.MainKt$main$9.invoke(Main.kt)
docker-compose-wallet-api-1         |   at id.walt.webwallet.MainKt$main$9.invoke(Main.kt)
docker-compose-wallet-api-1         |   at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:270)
docker-compose-wallet-api-1         |   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
docker-compose-wallet-api-1         |   at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
docker-compose-wallet-api-1         |   at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
docker-compose-wallet-api-1         |   at id.walt.webwallet.MainKt.main(Main.kt)
docker-compose-wallet-api-1         |
docker-compose-wallet-api-1         | ---- ^^^ Configuration error ^^^ ---
docker-compose-wallet-api-1         |
docker-compose-wallet-api-1         | 1786 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "tenant" (TenantConfig)...
docker-compose-wallet-api-1         | 1854 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "push" (PushConfig)...
docker-compose-wallet-api-1         | 1894 [main] INFO id.walt.webwallet.config.ConfigManager - OPTIONAL configuration "push" not loaded: Could not instantiate 'id.walt.webwallet.config.PushConfig' because:, 'pushPublicKey': Missing from config, 'pushPrivateKey': Missing from config, 'pushSubject': Missing from config [This is not a mistake if you are not using named feature. The feature will not be available when not configured.]
docker-compose-wallet-api-1         | 1894 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "wallet" (RemoteWalletConfig)...
docker-compose-wallet-api-1         | 1932 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "marketplace" (MarketPlaceConfiguration)...
docker-compose-wallet-api-1         | 2032 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "chainexplorer" (ChainExplorerConfiguration)...
docker-compose-wallet-api-1         | 2099 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "runtime" (RuntimeConfig)...
docker-compose-wallet-api-1         | 2127 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "oidc" (OidcConfiguration)...
docker-compose-wallet-api-1         | 2206 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "trust" (TrustConfig)...
docker-compose-wallet-api-1         | 2257 [main] INFO id.walt.webwallet.config.ConfigManager - OPTIONAL configuration "trust" not loaded: Could not instantiate 'id.walt.webwallet.config.TrustConfig' because:, 'issuersRecord': - Could not instantiate 'id.walt.webwallet.config.TrustConfig.TrustRecord' because:, 'governanceRecordPath': Missing from config, 'verifiersRecord': - Could not instantiate 'id.walt.webwallet.config.TrustConfig.TrustRecord' because:, 'governanceRecordPath': Missing from config [This is not a mistake if you are not using named feature. The feature will not be available when not configured.]
docker-compose-wallet-api-1         | 2257 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "rejectionreason" (RejectionReasonConfig)...
docker-compose-wallet-api-1         | 2278 [main] INFO id.walt.webwallet.config.ConfigManager - OPTIONAL configuration "rejectionreason" not loaded: Could not instantiate 'id.walt.webwallet.config.RejectionReasonConfig' because:, 'reasons': Missing from config [This is not a mistake if you are not using named feature. The feature will not be available when not configured.]
docker-compose-wallet-api-1         | 2278 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "registration-defaults" (RegistrationDefaultsConfig)...
docker-compose-wallet-api-1         | 2341 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "oci" (OciKeyConfig)...
docker-compose-wallet-api-1         | 2393 [main] INFO id.walt.webwallet.config.ConfigManager - OPTIONAL configuration "oci" not loaded: Could not instantiate 'id.walt.webwallet.config.OciKeyConfig' because:, 'tenancyOcid': Missing from config, 'compartmentOcid': Missing from config, 'userOcid': Missing from config, 'fingerprint': Missing from config, 'managementEndpoint': Missing from config, 'cryptoEndpoint': Missing from config [This is not a mistake if you are not using named feature. The feature will not be available when not configured.]
docker-compose-wallet-api-1         | 2394 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "notification" (NotificationConfig)...
docker-compose-wallet-api-1         | 2439 [main] INFO id.walt.webwallet.config.ConfigManager - OPTIONAL configuration "notification" not loaded: Could not instantiate 'id.walt.webwallet.config.NotificationConfig' because:, 'url': Missing from config [This is not a mistake if you are not using named feature. The feature will not be available when not configured.]
docker-compose-wallet-api-1         | 2439 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading required configuration: "db.sqlite" (DatasourceJsonConfiguration)...
docker-compose-wallet-api-1         | 2479 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading required configuration: "db.sqlite" (DatasourceConfiguration)...
docker-compose-wallet-api-1         | 2538 [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
docker-compose-wallet-api-1         | 3102 [main] INFO com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@1b15f922
docker-compose-wallet-api-1         | 3107 [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
docker-compose-wallet-api-1         | 3114 [main] INFO id.walt.webwallet.Main - Setting up...
docker-compose-wallet-api-1         | 3913 [main] INFO id.walt.webwallet.db.Db - Will use sqlite database (jdbc:sqlite:data/data.db), working directory: /waltid-wallet-api/.
docker-compose-wallet-api-1         | 3915 [main] INFO id.walt.webwallet.db.Db - Connecting to database at "jdbc:sqlite:data/data.db"...
docker-compose-wallet-api-1         | 4077 [main] DEBUG Exposed - DROP TABLE IF EXISTS wallet_issuers
docker-compose-wallet-api-1         | 4086 [main] DEBUG Exposed - DROP TABLE IF EXISTS credential_category
docker-compose-wallet-api-1         | 4092 [main] DEBUG Exposed - DROP TABLE IF EXISTS category
docker-compose-wallet-api-1         | 4131 [main] INFO Exposed - Preparing create tables statements took 38ms
docker-compose-wallet-api-1         | 4132 [main] DEBUG Exposed - CREATE TABLE IF NOT EXISTS wallet_issuers (id BINARY(16) NOT NULL PRIMARY KEY, wallet BINARY(16) NOT NULL, did VARCHAR(1024) NOT NULL, description TEXT DEFAULT 'no description' NULL, ui VARCHAR(128) NOT NULL, configuration VARCHAR(256) NOT NULL, authorized BOOLEAN DEFAULT 0 NOT NULL, CONSTRAINT fk_wallet_issuers_wallet__id FOREIGN KEY (wallet) REFERENCES wallets(id) ON DELETE RESTRICT ON UPDATE RESTRICT)
docker-compose-wallet-api-1         | 4135 [main] DEBUG Exposed - CREATE UNIQUE INDEX wallet_issuers_wallet_did ON wallet_issuers (wallet, did)
docker-compose-wallet-api-1         | 4139 [main] DEBUG Exposed - CREATE TABLE IF NOT EXISTS category (id INTEGER PRIMARY KEY AUTOINCREMENT, wallet BINARY(16) NOT NULL, "name" VARCHAR(128) NOT NULL, CONSTRAINT fk_category_wallet__id FOREIGN KEY (wallet) REFERENCES wallets(id) ON DELETE RESTRICT ON UPDATE RESTRICT)
docker-compose-wallet-api-1         | 4141 [main] DEBUG Exposed - CREATE UNIQUE INDEX category_wallet_name ON category (wallet, "name")
docker-compose-wallet-api-1         | 4143 [main] DEBUG Exposed - CREATE TABLE IF NOT EXISTS credential_category (wallet BINARY(16) NOT NULL, credential VARCHAR(256) NOT NULL, category INT NOT NULL, CONSTRAINT pk_credential_category PRIMARY KEY (wallet, credential, category), CONSTRAINT fk_credential_category_category__id FOREIGN KEY (category) REFERENCES category(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_credential_category_wallet_credential__wallet_id FOREIGN KEY (wallet, credential) REFERENCES credentials(wallet, id) ON DELETE RESTRICT ON UPDATE RESTRICT)
docker-compose-wallet-api-1         | 4180 [main] INFO Exposed - Executing create tables statements took 49ms
docker-compose-wallet-api-1         | 4242 [main] INFO Exposed - Extracting table columns took 62ms
docker-compose-wallet-api-1         | 4414 [main] INFO Exposed - Extracting primary keys took 172ms
docker-compose-wallet-api-1         | 4418 [main] INFO Exposed - Preparing alter table statements took 238ms
docker-compose-wallet-api-1         | 4421 [main] INFO Exposed - Executing alter table statements took 2ms
docker-compose-wallet-api-1         | 4556 [main] INFO Exposed - Index on table 'accounts' differs only in name: in db accounts_id -> in mapping accounts_id_unique
docker-compose-wallet-api-1         | 4557 [main] INFO Exposed - Index on table 'accounts' differs only in name: in db accounts_email -> in mapping accounts_email_unique
docker-compose-wallet-api-1         | 4561 [main] INFO Exposed - Index on table 'web3wallets' differs only in name: in db web3wallets_address -> in mapping web3wallets_address_unique
docker-compose-wallet-api-1         | 4562 [main] INFO Exposed - Index on table 'wallet_issuers' differs only in name: in db wallet_issuers_wallet_did -> in mapping wallet_issuers_wallet_did_unique
docker-compose-wallet-api-1         | 4562 [main] INFO Exposed - Index on table 'category' differs only in name: in db category_wallet_name -> in mapping category_wallet_name_unique
docker-compose-wallet-api-1         | 4563 [main] INFO Exposed - Index on table 'oidclogins' differs only in name: in db oidclogins_oidcId -> in mapping oidclogins_oidcId_unique
docker-compose-wallet-api-1         | 4563 [main] INFO Exposed - Index on table 'entity_name_resolution_cache' differs only in name: in db entity_name_resolution_cache_did -> in mapping entity_name_resolution_cache_did_unique
docker-compose-wallet-api-1         | 4566 [main] INFO Exposed - Checking mapping consistence took 145ms
docker-compose-wallet-api-1         | 4601 [main] INFO id.walt.webwallet.Main - Starting web server (binding to 0.0.0.0, listening on port 7001) ...
docker-compose-wallet-api-1         | 4610 [main] DEBUG id.walt.webwallet.Main - Available Processors: 12
docker-compose-wallet-api-1         | 4663 [DefaultDispatcher-worker-1] INFO ktor.application - Autoreload is disabled because the development mode is off.
docker-compose-wallet-api-1         | Exception in thread "main" java.lang.ExceptionInInitializerError
docker-compose-wallet-api-1         |   at id.walt.webwallet.web.controllers.AuthControllerKt$configureSecurity$1.invoke(AuthController.kt:87)
docker-compose-wallet-api-1         |   at id.walt.webwallet.web.controllers.AuthControllerKt$configureSecurity$1.invoke(AuthController.kt:78)
docker-compose-wallet-api-1         |   at io.ktor.server.application.CreatePluginUtilsKt.createRouteScopedPluginInstance(CreatePluginUtils.kt:284)
docker-compose-wallet-api-1         |   at io.ktor.server.application.CreatePluginUtilsKt.access$createRouteScopedPluginInstance(CreatePluginUtils.kt:1)
docker-compose-wallet-api-1         |   at io.ktor.server.application.CreatePluginUtilsKt$createRouteScopedPlugin$1.install(CreatePluginUtils.kt:137)
docker-compose-wallet-api-1         |   at io.ktor.server.application.CreatePluginUtilsKt$createRouteScopedPlugin$1.install(CreatePluginUtils.kt:123)
docker-compose-wallet-api-1         |   at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:100)
docker-compose-wallet-api-1         |   at id.walt.webwallet.web.controllers.AuthControllerKt.configureSecurity(AuthController.kt:78)
docker-compose-wallet-api-1         |   at id.walt.webwallet.MainKt.configurePlugins(Main.kt:63)
docker-compose-wallet-api-1         |   at id.walt.webwallet.MainKt.webWalletModule(Main.kt:76)
docker-compose-wallet-api-1         |   at id.walt.webwallet.MainKt.webWalletModule$default(Main.kt:74)
docker-compose-wallet-api-1         |   at id.walt.webwallet.MainKt$main$7.invoke(Main.kt:46)
docker-compose-wallet-api-1         |   at id.walt.webwallet.MainKt$main$7.invoke(Main.kt:46)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.internal.CallableUtilsKt.executeModuleFunction(CallableUtils.kt:51)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:332)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:331)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:356)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.launchModuleByName(ApplicationEngineEnvironmentReloading.kt:331)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$launchModuleByName(ApplicationEngineEnvironmentReloading.kt:32)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:319)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:310)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:338)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:310)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
docker-compose-wallet-api-1         |   at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
docker-compose-wallet-api-1         |   at io.ktor.server.cio.CIOApplicationEngine$initServerJob$1$2.invokeSuspend(CIOApplicationEngine.kt:207)
docker-compose-wallet-api-1         |   at io.ktor.server.cio.CIOApplicationEngine$initServerJob$1$2.invoke(CIOApplicationEngine.kt)
docker-compose-wallet-api-1         |   at io.ktor.server.cio.CIOApplicationEngine$initServerJob$1$2.invoke(CIOApplicationEngine.kt)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
docker-compose-wallet-api-1         |   at io.ktor.server.cio.CIOApplicationEngine$initServerJob$1.invokeSuspend(CIOApplicationEngine.kt:206)
docker-compose-wallet-api-1         |   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
docker-compose-wallet-api-1         |   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
docker-compose-wallet-api-1         | Caused by: io.ktor.server.plugins.NotFoundException: No loaded configuration: "auth"
docker-compose-wallet-api-1         |   at id.walt.webwallet.web.controllers.AuthKeys.<clinit>(AuthController.kt:590)
docker-compose-wallet-api-1         |   ... 40 more
docker-compose-wallet-api-1 exited with code 1
```

**Comment by inlorite** [comment]
From what I understand there is some default configuration missing. This is a fragment from the error above:

`docker-compose-wallet-api-1         | 1716 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading required configuration: "auth" (AuthConfig)... docker-compose-wallet-api-1         | 1785 [main] ERROR id.walt.webwallet.config.ConfigManager - ---- vvv Configuration error vvv ---- docker-compose-wallet-api-1         | Could not load configuration for "auth": com.sksamuel.hoplite.ConfigException: Error loading config because: docker-compose-wallet-api-1         | docker-compose-wallet-api-1         |     - Could not instantiate 'id.walt.webwallet.config.AuthConfig' because: docker-compose-wallet-api-1         | docker-compose-wallet-api-1         |         - 'encryptionKey': Missing from config docker-compose-wallet-api-1         | docker-compose-wallet-api-1         |         - 'signKey': Missing from config docker-compose-wallet-api-1         | docker-compose-wallet-api-1         |         - 'tokenKey': Missing from config docker-compose-wallet-api-1         | docker-compose-wallet-api-1         |         - 'issTokenClaim': Missing from config docker-compose-wallet-api-1         | docker-compose-wallet-api-1         |         - 'audTokenClaim': Missing from config docker-compose-wallet-api-1`

**Comment by mikeplotean** [comment]
this should be fixed now
also feel free to check out the latest release [v0.3.0](https://github.com/walt-id/waltid-identity/releases/tag/v0.3.0)
