### ISSUE TITLE
SDK - Verify VP with JwtSignaturePolicy error

### ISSUE THREAD

**Issue by myrtp** [walt-id/waltid-identity#401]
Hello,

I am using walt.id SDK to verify programmatically an VP that I previously issued also with the SDK.

I am using:
- Language: **Java**
- walt.id version: **id.walt.credentials:waltid-verifiable-credentials-jvm:0.2.0**
- DID method: did:key
- DID Key: **Ed25519**

When trying to verify the JWT VP with the SDK the policy JwtSignaturePolicy fails with error `No resolver for did method: key`.

Here's an example:
``` java
public Boolean verifyAgentVP(String vpJwt) throws InterruptedException, ExecutionException {
//      Initialize presentationVerifier
        PresentationVerifier presentationVerifier = new PresentationVerifier();
//        Initialize Policies to be checked
        JwtSignaturePolicy jwtSignaturePolicy = new JwtSignaturePolicy();

//      Initialize Policy Types
        List<PolicyRequest> vpPolicies = new ArrayList<>();
        List<PolicyRequest> globalVcPolicies = new ArrayList<>();
        HashMap<String, List<PolicyRequest>> specificCredentialPolicies = new HashMap<>();
        HashMap<String, Object> presentationContext = new HashMap<>();

        globalVcPolicies.add(new PolicyRequest(jwtSignaturePolicy, null));

        CompletableFuture<PresentationVerificationResponse> verificationFuture = presentationVerifier.verifyPresentationAsync(
                vpJwt, vpPolicies, globalVcPolicies, specificCredentialPolicies, presentationContext);

        PresentationVerificationResponse response = verificationFuture.get();

        return response.overallSuccess();
    }
```

The `presentationVerifier.verifyPresentationAsync()` is just a wrapper of walt.id's SDK.
``` java
....
            // Execute verifyPresentation method asynchronously
            Verifier.INSTANCE.verifyPresentation(
                    signedPresentation, vpPolicies, globalVcPolicies,
                    specificCredentialPolicies, presentationContext, continuationVp);
....
```

The response of `verificationFuture.get();` has the following error:

```
java.lang.IllegalArgumentException: No resolver for did method: key
	at id.walt.did.dids.DidService.getResolverForDid(DidService.kt:129)
	at id.walt.did.dids.DidService.resolveToKey-gIAlu-s(DidService.kt:145)
	at id.walt.credentials.schemes.JwsSignatureScheme.verify-gIAlu-s(JwsSignatureScheme.kt:78)
	at id.walt.credentials.verification.policies.JwtSignaturePolicy.verify-BWLJW6A(JwtSignaturePolicy.kt:22)
	at id.walt.credentials.verification.Verifier.runPolicyRequest-BWLJW6A(Verifier.kt:44)
	at id.walt.credentials.verification.Verifier$runPolicyRequests$2$1$1.invokeSuspend(Verifier.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

Example JWT VP [found in walt.id's Documentation ](https://docs.oss.walt.id/issuer/sdks/manage-credentials/present/w3c-credential#signing-a-verifiable-presentation) also fails:

`eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImRpZDprZXk6ejZNa3B1aWhYcW40ajdkbTRxcFMxZVA5TVIyU3Nkb0NGdVdoZFRZRjh6R1V1SEZaI3o2TWtwdWloWHFuNGo3ZG00cXBTMWVQOU1SMlNzZG9DRnVXaGRUWUY4ekdVdUhGWiJ9.eyJzdWIiOiJkaWQ6a2V5Ono2TWtwdWloWHFuNGo3ZG00cXBTMWVQOU1SMlNzZG9DRnVXaGRUWUY4ekdVdUhGWiIsIm5iZiI6MTcwNTQ5MzA0NCwiaWF0IjoxNzA1NDkzMTA0LCJqdGkiOiJ1cm46dXVpZDo1YTdlMjllMC0wNzdkLTRmZGQtYTFlMy1lN2QyYmVjNTBkYTYiLCJpc3MiOiJkaWQ6a2V5Ono2TWtwdWloWHFuNGo3ZG00cXBTMWVQOU1SMlNzZG9DRnVXaGRUWUY4ekdVdUhGWiIsIm5vbmNlIjoiMjAzOTQwMjkzNDAiLCJ2cCI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVQcmVzZW50YXRpb24iXSwiaWQiOiJ1cm46dXVpZDo1YTdlMjllMC0wNzdkLTRmZGQtYTFlMy1lN2QyYmVjNTBkYTYiLCJob2xkZXIiOiJkaWQ6a2V5Ono2TWtwdWloWHFuNGo3ZG00cXBTMWVQOU1SMlNzZG9DRnVXaGRUWUY4ekdVdUhGWiIsInZlcmlmaWFibGVDcmVkZW50aWFsIjpbImV5SmhiR2NpT2lKRlpFUlRRU0lzSW10cFpDSTZJbVJwWkRwclpYazZlalpOYTJWMVdIbDFXbU5JTVVNM2JtUkZjMFJyYVRGaVdqaFZOV2h4ZWxoaVlVUnViVFk1VlhWQ1kyOXBjbkJpSW4wLmV5SnBjM01pT2lKa2FXUTZhMlY1T25vMlRXdGxkVmg1ZFZwalNERkROMjVrUlhORWEya3hZbG80VlRWb2NYcFlZbUZFYm0wMk9WVjFRbU52YVhKd1lpSXNJbk4xWWlJNkltUnBaRHByWlhrNmVqWk5hM0IxYVdoWWNXNDBhamRrYlRSeGNGTXhaVkE1VFZJeVUzTmtiME5HZFZkb1pGUlpSamg2UjFWMVNFWmFJaXdpZG1NaU9uc2lRR052Ym5SbGVIUWlPbHNpYUhSMGNITTZMeTkzZDNjdWR6TXViM0puTHpJd01UZ3ZZM0psWkdWdWRHbGhiSE12ZGpFaUxDSm9kSFJ3Y3pvdkwzQjFjbXd1YVcxeloyeHZZbUZzTG05eVp5OXpjR1ZqTDI5aUwzWXpjREF2WTI5dWRHVjRkQzB6TGpBdU1pNXFjMjl1SWwwc0luUjVjR1VpT2xzaVZtVnlhV1pwWVdKc1pVTnlaV1JsYm5ScFlXd2lMQ0pQY0dWdVFtRmtaMlZEY21Wa1pXNTBhV0ZzSWwwc0ltTnlaV1JsYm5ScFlXeFRkV0pxWldOMElqcDdJblI1Y0dVaU9sc2lRV05vYVdWMlpXMWxiblJUZFdKcVpXTjBJbDBzSW1GamFHbGxkbVZ0Wlc1MElqcDdJbWxrSWpvaWRYSnVPblYxYVdRNllXTXlOVFJpWkRVdE9HWmhaQzAwWW1JeExUbGtNamt0Wldaa09UTTROVE0yT1RJMklpd2lkSGx3WlNJNld5SkJZMmhwWlhabGJXVnVkQ0pkTENKdVlXMWxJam9pU2taR0lIZ2dkbU10WldSMUlGQnNkV2RHWlhOMElETWdTVzUwWlhKdmNHVnlZV0pwYkdsMGVTSXNJbVJsYzJOeWFYQjBhVzl1SWpvaVZHaHBjeUIzWVd4c1pYUWdjM1Z3Y0c5eWRITWdkR2hsSUhWelpTQnZaaUJYTTBNZ1ZtVnlhV1pwWVdKc1pTQkRjbVZrWlc1MGFXRnNjeUJoYm1RZ2FHRnpJR1JsYlc5dWMzUnlZWFJsWkNCcGJuUmxjbTl3WlhKaFltbHNhWFI1SUdSMWNtbHVaeUIwYUdVZ2NISmxjMlZ1ZEdGMGFXOXVJSEpsY1hWbGMzUWdkMjl5YTJac2IzY2daSFZ5YVc1bklFcEdSaUI0SUZaRExVVkVWU0JRYkhWblJtVnpkQ0F6TGlJc0ltTnlhWFJsY21saElqcDdJblI1Y0dVaU9pSkRjbWwwWlhKcFlTSXNJbTVoY25KaGRHbDJaU0k2SWxkaGJHeGxkQ0J6YjJ4MWRHbHZibk1nY0hKdmRtbGtaWEp6SUdWaGNtNWxaQ0IwYUdseklHSmhaR2RsSUdKNUlHUmxiVzl1YzNSeVlYUnBibWNnYVc1MFpYSnZjR1Z5WVdKcGJHbDBlU0JrZFhKcGJtY2dkR2hsSUhCeVpYTmxiblJoZEdsdmJpQnlaWEYxWlhOMElIZHZjbXRtYkc5M0xpQlVhR2x6SUdsdVkyeDFaR1Z6SUhOMVkyTmxjM05tZFd4c2VTQnlaV05sYVhacGJtY2dZU0J3Y21WelpXNTBZWFJwYjI0Z2NtVnhkV1Z6ZEN3Z1lXeHNiM2RwYm1jZ2RHaGxJR2h2YkdSbGNpQjBieUJ6Wld4bFkzUWdZWFFnYkdWaGMzUWdkSGR2SUhSNWNHVnpJRzltSUhabGNtbG1hV0ZpYkdVZ1kzSmxaR1Z1ZEdsaGJITWdkRzhnWTNKbFlYUmxJR0VnZG1WeWFXWnBZV0pzWlNCd2NtVnpaVzUwWVhScGIyNHNJSEpsZEhWeWJtbHVaeUIwYUdVZ2NISmxjMlZ1ZEdGMGFXOXVJSFJ2SUhSb1pTQnlaWEYxWlhOMGIzSXNJR0Z1WkNCd1lYTnphVzVuSUhabGNtbG1hV05oZEdsdmJpQnZaaUIwYUdVZ2NISmxjMlZ1ZEdGMGFXOXVJR0Z1WkNCMGFHVWdhVzVqYkhWa1pXUWdZM0psWkdWdWRHbGhiSE11SW4wc0ltbHRZV2RsSWpwN0ltbGtJam9pYUhSMGNITTZMeTkzTTJNdFkyTm5MbWRwZEdoMVlpNXBieTkyWXkxbFpDOXdiSFZuWm1WemRDMHpMVEl3TWpNdmFXMWhaMlZ6TDBwR1JpMVdReTFGUkZVdFVFeFZSMFpGVTFRekxXSmhaR2RsTFdsdFlXZGxMbkJ1WnlJc0luUjVjR1VpT2lKSmJXRm5aU0o5ZlN3aWFXUWlPaUprYVdRNmEyVjVPbm8yVFd0elJtNWhlRFo0UTBKWFpHODJhR2htV2pkd1JYTmllV0Z4T1UxTlRtUnRRVUpUTVU1eVkwTkVXa3B5TXlKOUxDSnBaQ0k2SW5WeWJqcDFkV2xrT2pReE56ZGxNRFE0TFRsaE5HRXRORGMwWlMwNVpHTTJMV0ZsWkRSbE5qRmhOalF6T1NJc0ltbHpjM1ZsY2lJNkltUnBaRHByWlhrNmVqWk5hM05HYm1GNE5uaERRbGRrYnpab2FHWmFOM0JGYzJKNVlYRTVUVTFPWkcxQlFsTXhUbkpqUTBSYVNuSXpJaXdpYVhOemRXRnVZMlZFWVhSbElqb2lNakF5TkMwd01TMHhOMVF4TWpvd05Ub3dOQzR5TlRJMU16QmFJaXdpWlhod2FYSmhkR2x2YmtSaGRHVWlPaUl5TURJMExUQXhMVEU1VkRFeU9qQTFPakEwTGpJMU16QTNOVm9pTENKdVlXMWxJam9pU2taR0lIZ2dkbU10WldSMUlGQnNkV2RHWlhOMElETWdTVzUwWlhKdmNHVnlZV0pwYkdsMGVTSjlmUS4yLV9NaXc3RmpjdkpfUlBhYmVwS1VJeS01amZSajBoa2stTXRnUlNzMHlEaTFsZnlialE2cTh1Wks3cndPdEQyakc0ZC1mSzRSNmdMZTRheDMtU3JBQSJdfX0.rdLymfQCVHt-q-BQYvlGGiABkigkywdcIlPhVBCDJobpOmfhm-oOjmRQUi8NAFzZnRFlqGafHf59YqYIVbs2DA
`

**Comment by myrtp** [comment]
Thank you, this fixed the issue.
