### ISSUE TITLE
Docker compose doesn't expose postgres-1 to the $POSTGRES_DB_PORT

### ISSUE THREAD

**Issue by sekasx** [walt-id/waltid-identity#515]
Hello,

I am using the `docker-compose up` command to start the walt.id services (especially the wallet frontend).

Because in my machine I already have another Postgres instance running in port 5432, I changed the $POSTGRES_DB_PORT in 5433. When I run the `docker-compose up` command I get the following error:
```
 Exception in thread "main" java.lang.IllegalArgumentException: Could not initialize Hikari database connection pool configuration: Failed to initialize pool: The connection attempt failed.
wallet-api-1         |  at id.walt.webwallet.db.Db.connect(Db.kt:41)
wallet-api-1         |  at id.walt.webwallet.db.Db.start(Db.kt:107)
wallet-api-1         |  at id.walt.webwallet.MainKt$main$2.invokeSuspend(Main.kt:38)
```

### Steps to reproduce
- set `POSTGRES_DB_PORT=5433` in `.env`
- run `docker-compose up`

### How to fix it:
Postgres container always starts the DB in port 5432 internally. So port "5432" needs to be mapped in $POSTGRES_DB_PORT.
So this:
```
    ports:
      - $POSTGRES_DB_PORT:$POSTGRES_DB_PORT #TODO: tcp/udp proxy with caddy
```
needs to change to this:
```
    ports:
      - $POSTGRES_DB_PORT:5432 #TODO: tcp/udp proxy with caddy
```

If you confirm this, I'd love to contribute this change. 
Please let me know if a PR is enough or if I need to follow another process.

**Comment by mikeplotean** [comment]
hi @sekasx, thanks for reporting that. It's been fixed as part of https://github.com/walt-id/waltid-identity/pull/513.
