### ISSUE TITLE
Error message improvement: No key was resolved when trying to resolve key to sign token

### ISSUE THREAD

**Issue by alegomes** [walt-id/waltid-identity#731]
I got this error when trying to use and offer request (/wallet-api/wallet/{wallet}/exchange/useOfferRequest) but it doesn't make sense to me, as a user.

```
No key was resolved when trying to resolve key to sign token
```

Wallet API log:

```
java.lang.IllegalStateException: No key was resolved when trying to resolve key to sign token
	at id.walt.webwallet.service.oidc4vc.TestCredentialWallet.tryResolveKeyId(TestCredentialWallet.kt:440)
	at id.walt.webwallet.service.oidc4vc.TestCredentialWallet.access$tryResolveKeyId(TestCredentialWallet.kt:63)
	at id.walt.webwallet.service.oidc4vc.TestCredentialWallet$signToken$1.invokeSuspend(TestCredentialWallet.kt:92)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at id.walt.webwallet.service.oidc4vc.TestCredentialWallet.signToken(TestCredentialWallet.kt:89)
	at id.walt.oid4vc.interfaces.ITokenProvider$DefaultImpls.signToken$default(ITokenProvider.kt:16)
	at id.walt.oid4vc.providers.OpenIDCredentialWallet.generateDidProof(OpenIDCredentialWallet.kt:71)
	at id.walt.oid4vc.providers.OpenIDCredentialWallet.generateDidProof$default(OpenIDCredentialWallet.kt:51)
	at id.walt.webwallet.service.exchange.ProofOfPossessionFactory.didProofOfPossession(ProofOfPossessionFactory.kt:29)
	at id.walt.webwallet.service.exchange.ProofOfPossessionFactory.new(ProofOfPossessionFactory.kt:21)
	at id.walt.webwallet.service.exchange.IssuanceService.processCredentialOffer(IssuanceService.kt:137)
	at id.walt.webwallet.service.exchange.IssuanceService.access$processCredentialOffer(IssuanceService.kt:37)
	at id.walt.webwallet.service.exchange.IssuanceService$processCredentialOffer$1.invokeSuspend(IssuanceService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

```

**Comment by SuperBatata** [comment]
The issue is thrown when the key is missing from the db , i suggest to have an extra verification step in the web-wallet before deleting the keys , something like a pop up saying : dids associated with this key will be no longer functional
