### ISSUE TITLE
Cannot run Docker image after following the instructions given in the docs

### ISSUE THREAD

**Issue by NikolaVetnic** [walt-id/waltid-identity#845]
## Describe the bug
When trying to run a container after cloning the repo and building the Docker image as described [here](https://docs.walt.id/community-stack/verifier/api/setup/open-source), the following output is received and the container doesn't run:
```shell
-- walt.id verifier [latest] --
Usage: service-runnable [<options>] [<config args>]...

Error: no such option --webHost
Error: no such option --webPort
Error: no such option --baseUrl
```

If I leave out the parameters the following output is received and the container doesn't run:
```shell
-- walt.id verifier [latest] --
09:58:15.553361171  INFO [                main] :        Configuration : Configuration set using the DSL with append=true
09:58:15.624894338  INFO [                main] :     walt.id verifier : Starting walt.id verifier [latest]...
09:58:15.643046213  INFO [                main] :         Feature-Init : Initializing features...
09:58:15.643165838  INFO [                main] :         Feature-Init : Registering common feature catalog...
09:58:15.648792880  INFO [                main] :         Feature-Init : Registering service feature catalog...
09:58:15.649594338  INFO [                main] :         Feature-Init : Loading features...
09:58:16.162226380  INFO [                main] :       FeatureManager : Disabled features (0):
09:58:16.162732922  INFO [                main] :       FeatureManager : Enabling base feature "verifier-service"...
09:58:16.163916463  INFO [                main] :       FeatureManager : ↳ Loading config "verifier-service" for feature "verifier-service"...
09:58:16.322447255 ERROR [                main] :        ConfigManager : ---- vvv Configuration error for "verifier-service" vvv ----
Could not load configuration for "verifier-service" (OIDCVerifierServiceConfig): com.sksamuel.hoplite.ConfigException: Error loading config because:

    - Could not instantiate 'id.walt.verifier.config.OIDCVerifierServiceConfig' because:

        - 'baseUrl': Missing String from config
	at com.sksamuel.hoplite.ConfigLoaderKt$returnOrThrow$1.invoke(ConfigLoader.kt:315)
	at com.sksamuel.hoplite.ConfigLoaderKt$returnOrThrow$1.invoke(ConfigLoader.kt:312)
	at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
	at com.sksamuel.hoplite.ConfigLoaderKt.returnOrThrow(ConfigLoader.kt:312)
	at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:273)
	at com.sksamuel.hoplite.ConfigLoader.loadConfigOrThrow(ConfigLoader.kt:130)
	at com.sksamuel.hoplite.ConfigLoader.loadConfigOrThrow$default(ConfigLoader.kt:129)
	at id.walt.commons.config.ConfigManager.loadConfig-gIAlu-s(ConfigManager.kt:65)
	at id.walt.commons.featureflag.FeatureManager.enableFeature-gIAlu-s(FeatureManager.kt:34)
	at id.walt.commons.featureflag.FeatureManager.load(FeatureManager.kt:155)
	at id.walt.commons.ServiceCommons.initFeatures(ServiceCommons.kt:54)
	at id.walt.commons.ServiceCommons.runService(ServiceCommons.kt:94)
	at id.walt.commons.commands.ServiceRunnableCommand$run$1.invokeSuspend(ServiceRunnableCommand.kt:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at id.walt.commons.commands.ServiceRunnableCommand.run(ServiceRunnableCommand.kt:38)
	at com.github.ajalt.clikt.core.CoreCliktCommandKt.parse(CoreCliktCommand.kt:107)
	at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:78)
	at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:90)
	at id.walt.commons.ServiceMain.main(ServiceMain.kt:15)
	at id.walt.verifier.MainKt.main(Main.kt:32)
	at id.walt.verifier.MainKt$main$4.invoke(Main.kt)
	at id.walt.verifier.MainKt$main$4.invoke(Main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:223)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at id.walt.verifier.MainKt.main(Main.kt)

---- ^^^ Configuration error for "verifier-service" ^^^ ---

09:58:16.323787130  INFO [                main] :       FeatureManager : Enabling base feature "web"...
09:58:16.323923172  INFO [                main] :       FeatureManager : ↳ Loading config "web" for feature "web"...
09:58:16.332260630  INFO [                main] :       FeatureManager : Enabled features (1): web
09:58:16.333350672  INFO [                main] :       FeatureManager : Defaulted features (8): lsp-potential, openapi, authservice, feature-flag-information-endpoint, healthchecks, persistence, entra, debug-endpoints
09:58:16.333723672  INFO [                main] :       FeatureManager : Enabling default feature "openapi"...
09:58:16.334490005  INFO [                main] :       FeatureManager : Enabling default feature "authservice"...
09:58:16.334558630  INFO [                main] :       FeatureManager : Enabling default feature "feature-flag-information-endpoint"...
09:58:16.334615672  INFO [                main] :       FeatureManager : Enabling default feature "healthchecks"...
09:58:16.334643588  INFO [                main] :       FeatureManager : Enabling default feature "debug-endpoints"...
09:58:16.336200005  INFO [                main] :       FeatureManager : ↳ Loading config "debug-endpoints" for feature "debug-endpoints"...
09:58:16.352961172 ERROR [                main] :       FeatureManager : 1 features failed to enable (see above for specifics) - error summary:
- Failure 1/1: Loading "verifier-service" failed: Error loading config because:
    - Could not instantiate 'id.walt.verifier.config.OIDCVerifierServiceConfig' because:
        - 'baseUrl': Missing String from config
```

## To Reproduce

1. Follow the three steps described [here](https://docs.walt.id/community-stack/verifier/api/setup/open-source).
2. See error(s) listed above when trying to run the container utilizing the command titled **Running the docker image**.

## Expected behavior

I expect the Docker image of the Verifier API to run in a container.

## Actual behavior

The Verifier API container doesn't run upon having been built.

## Environment

- os version: macOS Sequoia Version 15.1.1
- docker version: 4.20.1
- compose version: 2.18.1
- java version NA (I am trying to run a built image inside a container, not run a project locally)

## Screenshots

Not applicable.

## Additional context

None.

**Comment by NikolaVetnic** [comment]
Thank you very much for your response, this has helped me out a great deal and just in time :)
